import type { Metadata } from "next";
import { Inter, Lora, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "@/components/providers";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner";
// @ts-ignore - this file will be generated by the boneyard-js build step

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

import { globalMetadata, globalViewport } from "@/meta/global/layout";
import type { Viewport } from "next";

export const metadata: Metadata = globalMetadata;
export const viewport: Viewport = globalViewport;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      localization={{
        signIn: {
          start: {
            title: "Welcome to",
            subtitle: "Sign in or Create account to continue",
          },
        },
        signUp: {
          start: {
            title: "Welcome to",
            subtitle: "Sign in or Create account to continue",
          },
        },
      }}
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "var(--primary)",
          colorBackground: "var(--background)",
          colorText: "var(--foreground)",
          colorInputBackground: "var(--card)",
          colorInputText: "var(--foreground)",
          borderRadius: "var(--radius)",
        },
        elements: {
          card: "bg-card border border-border shadow-2xl mx-auto !my-auto",
          navbar: "bg-transparent",
          headerTitle: "text-2xl font-bold tracking-tight text-foreground after:content-['SlaveCode'] after:text-primary after:ml-2",
          headerSubtitle: "text-base text-muted-foreground",
          socialButtonsBlockButton:
            "bg-muted/50 border-border hover:bg-muted transition-all",
          formButtonPrimary:
            "bg-primary text-primary-foreground hover:opacity-90 transition-opacity",
          footerActionLink: "text-primary hover:text-primary/80",
          userButtonPopoverCard: "bg-card border border-border",
          modalContent: "flex items-center justify-center",
          modalBackdrop: "!bg-background/60 backdrop-blur-[2px] fixed inset-0 flex items-center justify-center z-[9999]",
          footer: "!hidden",
          footerInternal: "!hidden",
          watermark: "hidden",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            themes={[
              "dark",
              "theme-neutral",
              "theme-bubble-gum",
              "theme-twitter",
              "theme-claude",
              "theme-astro-vista",
              "theme-chalk",
              "theme-sandstone",
              "theme-cyber-yellow",
              "theme-meridian",
              "theme-discord",
              "theme-royal-gold",
            ]}
          >
            <Toaster position="top-center" />
            <Providers>
              <Navbar />
              {children}
              <Footer />
            </Providers>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
